### ISSUE TITLE
Klassenauswahl Einträge doppelt / unvollständig

### ISSUE THREAD

**Issue by 9teufel** [oveleon/contao-component-style-manager#74]
In einer frischen Contao 4.13 Installation mit Thememanager 1.5.2 und StyleManager Version 3.0.2 werden die Klassen in der Auswahl mehrfach bzw. unvollständig angezeigt.

Habe die style-manager-core.xml Bundle-Konfigurationen importiert, was eigentlich gar nicht notwendig ist.

**Comment by zoglo** [comment]
@9teufel 

https://github.com/contao-thememanager/core/releases/tag/1.5.0

The important information is within the UPGRADE.md and the release notes above
- https://github.com/contao-thememanager/core/blob/1.5.0/UPGRADE.md#v15-stylemanager-archives

Due to the new bundle configuration, you do not need the style manager archives anymore.
However, do export your settings if you've ever changed anything within the ContaoThemeManager-Framework StyleManager archives.

The reason why it's showing twice is because aliases did change and you are importing the bundle config + merging your archives that are saved in your database.
