### ISSUE TITLE
FR: Disable the SCSS cache

### ISSUE THREAD

**Issue by Aybee** [oveleon/contao-component-style-manager#86]
Hello, I like this extension. I also tried [theme-toolbox](https://github.com/erdmannfreunde/theme-toolbox) but your extension has more options. But theme-toolbox has this nice feature to deactivate the SCSS cache. Will you please add this feature to your extension so I don't have to install both extensions?
https://github.com/erdmannfreunde/theme-toolbox/issues/15#issuecomment-1548349330

**Comment by fritzmg** [comment]
The SCSS "cache" isn't really related to this extension?

**Comment by Aybee** [comment]
Yes I know, but there is no other extension that provides this. Or is there?

**Comment by fritzmg** [comment]
You could add [the listener](https://github.com/erdmannfreunde/theme-toolbox/blob/2.x/src/EventListener/DisableCssCachingListener.php) as an App customisation - or provide it in your own extension.

**Comment by Aybee** [comment]
Ok, thank you very much. Don't know how to do it, but maybe come back to it later.

**Comment by Aybee** [comment]
Ok, worth a try. Thank you.

I think the theme compiler is not what I need. I edit SCSS files directly on the server and would then like to be able to see the CSS result directly in the FE.

Contao already compiles SCSS files very well, but not when I edit the files with my editor on the server.

I will then first of all install both extensions, component-style-manager and theme-toolbox. Unfortunately, erdmannfreunde don't want to include the options for news etc. in its extension.

**Comment by zoglo** [comment]
Mind that the theme compiler uses the same technique (scssphp) + having ready to ship out CSS files in your layout means less stress for your server.

I usually just change my files and upload them and compile via ssh when I'm done for a few of our projects.

The common practice nowadays (it's still personal preference for most people) is compiling locally, especially since libraries like scssphp still don't support dartsass with use and forward.

Just because it's supported, doesn't mean it's good practice when a feature like disabling the scss cache is needed if you know what I mean.

**Comment by Aybee** [comment]
It's only for developement, not for going live. You can switch it on and off with theme-toolbox.

**Comment by zoglo** [comment]
Closed as invalid
